// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterApplicationSetSyncStrategies implements ClusterApplicationSetSyncStrategyInterface
type FakeClusterApplicationSetSyncStrategies struct {
	Fake *FakeArgoprojV1alpha1
	ns   string
}

var clusterapplicationsetsyncstrategiesResource = schema.GroupVersionResource{Group: "argoproj.io", Version: "v1alpha1", Resource: "clusterapplicationsetsyncstrategies"}

var clusterapplicationsetsyncstrategiesKind = schema.GroupVersionKind{Group: "argoproj.io", Version: "v1alpha1", Kind: "ClusterApplicationSetSyncStrategy"}

// Get takes name of the clusterApplicationSetSyncStrategy, and returns the corresponding clusterApplicationSetSyncStrategy object, and an error if there is any.
func (c *FakeClusterApplicationSetSyncStrategies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterApplicationSetSyncStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterapplicationsetsyncstrategiesResource, c.ns, name), &v1alpha1.ClusterApplicationSetSyncStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterApplicationSetSyncStrategy), err
}

// List takes label and field selectors, and returns the list of ClusterApplicationSetSyncStrategies that match those selectors.
func (c *FakeClusterApplicationSetSyncStrategies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterApplicationSetSyncStrategyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterapplicationsetsyncstrategiesResource, clusterapplicationsetsyncstrategiesKind, c.ns, opts), &v1alpha1.ClusterApplicationSetSyncStrategyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterApplicationSetSyncStrategyList{ListMeta: obj.(*v1alpha1.ClusterApplicationSetSyncStrategyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterApplicationSetSyncStrategyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterApplicationSetSyncStrategies.
func (c *FakeClusterApplicationSetSyncStrategies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterapplicationsetsyncstrategiesResource, c.ns, opts))

}

// Create takes the representation of a clusterApplicationSetSyncStrategy and creates it.  Returns the server's representation of the clusterApplicationSetSyncStrategy, and an error, if there is any.
func (c *FakeClusterApplicationSetSyncStrategies) Create(ctx context.Context, clusterApplicationSetSyncStrategy *v1alpha1.ClusterApplicationSetSyncStrategy, opts v1.CreateOptions) (result *v1alpha1.ClusterApplicationSetSyncStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterapplicationsetsyncstrategiesResource, c.ns, clusterApplicationSetSyncStrategy), &v1alpha1.ClusterApplicationSetSyncStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterApplicationSetSyncStrategy), err
}

// Update takes the representation of a clusterApplicationSetSyncStrategy and updates it. Returns the server's representation of the clusterApplicationSetSyncStrategy, and an error, if there is any.
func (c *FakeClusterApplicationSetSyncStrategies) Update(ctx context.Context, clusterApplicationSetSyncStrategy *v1alpha1.ClusterApplicationSetSyncStrategy, opts v1.UpdateOptions) (result *v1alpha1.ClusterApplicationSetSyncStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterapplicationsetsyncstrategiesResource, c.ns, clusterApplicationSetSyncStrategy), &v1alpha1.ClusterApplicationSetSyncStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterApplicationSetSyncStrategy), err
}

// Delete takes name of the clusterApplicationSetSyncStrategy and deletes it. Returns an error if one occurs.
func (c *FakeClusterApplicationSetSyncStrategies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusterapplicationsetsyncstrategiesResource, c.ns, name, opts), &v1alpha1.ClusterApplicationSetSyncStrategy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterApplicationSetSyncStrategies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterapplicationsetsyncstrategiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterApplicationSetSyncStrategyList{})
	return err
}

// Patch applies the patch and returns the patched clusterApplicationSetSyncStrategy.
func (c *FakeClusterApplicationSetSyncStrategies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterApplicationSetSyncStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterapplicationsetsyncstrategiesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterApplicationSetSyncStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterApplicationSetSyncStrategy), err
}
