apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: syncstrategies.argoproj.io
    app.kubernetes.io/part-of: argocd
  name: syncstrategies.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: SyncStrategy
    listKind: SyncStrategyList
    plural: syncstrategies
    singular: syncstrategy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: 'SyncStrategy is the definition of a sync strategy for an application.
          It is used to determine the order and timing of sync operations for applications within an ApplicationSet.'
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SyncStrategySpec is the specification of a SyncStrategy
            properties:
              rollingSync:
                properties:
                  steps:
                    items:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            type: object
                          type: array
                        maxUpdate:
                          anyOf:
                          - type: integer
                          - type: string
                          x-kubernetes-int-or-string: true
                      type: object
                    type: array
                type: object
              type:
                type: string
            type: object
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
